### ISSUE TITLE
bullet appear timing

### ISSUE THREAD

**Issue by LeaYeh** [pi314/todo-or-not-todo.vim#4]
@pi314 thank for #3 , todo-list plugin is more friendly then before :)
if current bullet with no string behind, new line should not create a new bullet, i think it will be more friendly and instinctive :)

**Comment by pi314** [comment]
@LeaYeh What are you saying is #1 XD
I'm thinking a clean way to do it~

**Comment by LeaYeh** [comment]
oh no detail so i forgot it, sorry for that.

**Comment by LeaYeh** [comment]
@pi314  another problem is, when i use vim auto complete something is going wrong, 
e.g.
[ ] some string (auto complete -> enter)
checkbox will be changed to bullet!

**Comment by pi314** [comment]
O....k, I'll see what's going on O_O
